version: '3.8'


services:
  flask-app:
    image: shayle/shay-wog:1.08
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./scores.txt:/scores.txt