version: '3.8'


services:
  flask-app:
    image: shay-wog:1.08
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - C:\Users\shayle\PycharmProjects\Shay-DevOps\scores.txt:/scores.txt